#!/usr/bin/env python3

from dependencies import check_dependencies


def main():
    missing = check_dependencies()
    if missing:
        missing = ", ".join(missing)
        print(
            f"Error: ensure the following dependencies are installed and configured. {missing}"
        )
        return


if __name__ == "__main__":
    main()
