#!/usr/bin/env python3

import args
from utils.dependencies import check_dependencies


def main():
    missing = check_dependencies()
    if missing:
        missing = ", ".join(missing)
        print(
            f"Ensure the following dependencies are installed and configured: {missing}"
        )
        return
    args.setup_argparse()


if __name__ == "__main__":
    main()
